"use server";

import { z } from "zod";
import { createClient } from "@supabase/supabase-js";
import { Resend } from "resend";

// ── Clients ───────────────────────────────────────────────────────────────────
// Use service role so unauthenticated insert bypasses RLS cleanly.

const supabaseAdmin = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL!,
  process.env.SUPABASE_SERVICE_ROLE_KEY!,
);

const resend = new Resend(process.env.RESEND_API_KEY);

const SENDER_EMAIL =
  process.env.NODE_ENV === "production"
    ? (process.env.PROD_EMAIL ?? "noreply@kibali.ac.ke")
    : "onboarding@resend.dev";

const ADMISSIONS_EMAIL =
  process.env.ADMISSIONS_EMAIL ?? "admissions@kibali.ac.ke";

const DEV_EMAIL = process.env.DEV_EMAIL ?? "omollondrw@gmail.com";

function resolveRecipient(email: string): string {
  return process.env.NODE_ENV === "production" ? email : DEV_EMAIL;
}

// ── Validation schema ─────────────────────────────────────────────────────────

const publicApplicationSchema = z.object({
  studentFirstName: z.string().min(2).max(50),
  studentLastName: z.string().min(2).max(50),
  studentGender: z.enum(["male", "female", "other"]),
  studentDOB: z.string().min(1),
  currentGrade: z.string().min(1).max(20),
  applyingForGrade: z.string().min(1).max(30),
  parentFirstName: z.string().min(2).max(50),
  parentLastName: z.string().min(2).max(50),
  parentEmail: z.string().email(),
  parentPhone: z.string().min(7).max(20),
  parentRelationship: z.enum(["mother", "father", "guardian", "other"]),
  address: z.string().max(200).optional().nullable(),
  city: z.string().max(50).optional().nullable(),
  postalCode: z.string().max(20).optional().nullable(),
  previousSchool: z.string().max(100).optional().nullable(),
  specialNeeds: z.string().max(500).optional().nullable(),
  interests: z.string().max(500).optional().nullable(),
  agreeToTerms: z.boolean().refine((v) => v === true),
  receiveUpdates: z.boolean().optional().default(false),
});

export type PublicApplicationInput = z.infer<typeof publicApplicationSchema>;

export interface ApplicationResult {
  success: boolean;
  message: string;
  referenceNumber?: string;
}

// ── Action ────────────────────────────────────────────────────────────────────

export async function submitPublicApplication(
  input: PublicApplicationInput,
): Promise<ApplicationResult> {
  // 1. Validate
  const parsed = publicApplicationSchema.safeParse(input);
  if (!parsed.success) {
    return {
      success: false,
      message: parsed.error.issues[0]?.message ?? "Invalid form data.",
    };
  }

  const d = parsed.data;

  // 2. Insert — reference_number is auto-generated by DB trigger
  const { data: row, error: insertError } = await supabaseAdmin
    .from("public_applications")
    .insert({
      student_first_name: d.studentFirstName,
      student_last_name: d.studentLastName,
      student_gender: d.studentGender,
      student_dob: d.studentDOB,
      current_grade: d.currentGrade,
      applying_for_grade: d.applyingForGrade,
      parent_first_name: d.parentFirstName,
      parent_last_name: d.parentLastName,
      parent_email: d.parentEmail,
      parent_phone: d.parentPhone,
      parent_relationship: d.parentRelationship,
      address: d.address ?? null,
      city: d.city ?? null,
      postal_code: d.postalCode ?? null,
      previous_school: d.previousSchool ?? null,
      special_needs: d.specialNeeds ?? null,
      interests: d.interests ?? null,
      agree_to_terms: d.agreeToTerms,
      receive_updates: d.receiveUpdates ?? false,
      reference_number: "", // trigger overwrites this
    })
    .select("reference_number")
    .single();

  if (insertError || !row) {
    console.error("Application insert error:", insertError?.message);
    return {
      success: false,
      message: "We couldn't save your application. Please try again.",
    };
  }

  const ref = row.reference_number;
  const parentName = `${d.parentFirstName} ${d.parentLastName}`;
  const studentName = `${d.studentFirstName} ${d.studentLastName}`;

  // 3. Send acknowledgement email to parent
  try {
    await resend.emails.send({
      from: `Kibali Academy Admissions <${SENDER_EMAIL}>`,
      to: resolveRecipient(d.parentEmail),
      subject: `Application Received – ${ref}`,
      html: buildAcknowledgementEmail({
        parentName,
        studentName,
        ref,
        applyingForGrade: d.applyingForGrade,
      }),
    });
  } catch (mailErr) {
    console.error("Acknowledgement email failed:", mailErr);
    // Non-fatal
  }

  // 4. Alert admissions team
  try {
    await resend.emails.send({
      from: `Kibali Admissions Bot <${SENDER_EMAIL}>`,
      to: resolveRecipient(ADMISSIONS_EMAIL),
      subject: `New Application: ${studentName} (${ref})`,
      html: buildAdminAlertEmail({
        studentName,
        parentName,
        ref,
        applyingForGrade: d.applyingForGrade,
        parentEmail: d.parentEmail,
        parentPhone: d.parentPhone,
      }),
    });
  } catch (alertErr) {
    console.error("Admin alert email failed:", alertErr);
    // Non-fatal
  }

  return {
    success: true,
    message: "Application submitted successfully.",
    referenceNumber: ref,
  };
}

// ── Email builders ────────────────────────────────────────────────────────────

function buildAcknowledgementEmail({
  parentName,
  studentName,
  ref,
  applyingForGrade,
}: {
  parentName: string;
  studentName: string;
  ref: string;
  applyingForGrade: string;
}): string {
  return `<!DOCTYPE html>
<html lang="en">
<head><meta charset="UTF-8"/><meta name="viewport" content="width=device-width,initial-scale=1.0"/></head>
<body style="margin:0;padding:0;background:#f1f5f9;font-family:'Segoe UI',Tahoma,Geneva,Verdana,sans-serif;">
  <table width="100%" cellpadding="0" cellspacing="0" border="0" style="background:#f1f5f9;padding:40px 16px;">
    <tr><td align="center">
      <table width="600" cellpadding="0" cellspacing="0" border="0" style="max-width:600px;width:100%;background:#ffffff;border-radius:16px;overflow:hidden;box-shadow:0 4px 24px rgba(0,0,0,0.08);">
        <!-- Header -->
        <tr>
          <td style="background:#0c1f3f;padding:32px;">
            <p style="margin:0;font-size:10px;font-weight:800;letter-spacing:0.14em;text-transform:uppercase;color:rgba(255,255,255,0.55);">Kibali Academy</p>
            <p style="margin:6px 0 0;font-size:24px;font-weight:800;color:#ffffff;">Application Received 🎉</p>
            <p style="margin:6px 0 0;font-size:13px;color:rgba(255,255,255,0.6);">We've got your application — here's what happens next.</p>
          </td>
        </tr>
        <tr><td style="height:4px;background:#f59e0b;"></td></tr>
        <!-- Body -->
        <tr>
          <td style="padding:36px 32px 28px;color:#1a202c;font-size:15px;line-height:1.7;">
            <p style="margin:0 0 16px;">Dear <strong>${parentName}</strong>,</p>
            <p style="margin:0 0 16px;">
              Thank you for applying to <strong>Kibali Academy</strong>. We've successfully received the application for
              <strong>${studentName}</strong> for <strong>${applyingForGrade}</strong>.
            </p>

            <!-- Reference box -->
            <table width="100%" cellpadding="0" cellspacing="0" border="0" style="margin:24px 0;">
              <tr>
                <td style="background:#f8fafc;border-left:4px solid #f59e0b;border-radius:8px;padding:16px 20px;">
                  <p style="margin:0;font-size:11px;font-weight:700;text-transform:uppercase;letter-spacing:0.1em;color:#64748b;">Application Reference</p>
                  <p style="margin:6px 0 0;font-size:22px;font-weight:800;color:#0c1f3f;letter-spacing:0.05em;">${ref}</p>
                  <p style="margin:4px 0 0;font-size:12px;color:#94a3b8;">Please quote this number in any correspondence with us.</p>
                </td>
              </tr>
            </table>

            <p style="margin:0 0 8px;font-weight:700;color:#0c1f3f;">What happens next?</p>
            <table width="100%" cellpadding="0" cellspacing="0" border="0" style="margin:0 0 24px;">
              ${[
                "Our admissions team will review your application within <strong>3 business days</strong>.",
                "We will contact you at <strong>" +
                  parentName +
                  "</strong>'s email to schedule an assessment or interview.",
                "Once a decision is made, you'll receive an offer letter or a detailed explanation.",
              ]
                .map(
                  (step, i) => `
              <tr>
                <td style="padding:8px 0;vertical-align:top;">
                  <table cellpadding="0" cellspacing="0" border="0"><tr>
                    <td style="width:28px;height:28px;background:#f59e0b;border-radius:50%;text-align:center;line-height:28px;font-size:12px;font-weight:800;color:#0c1f3f;vertical-align:middle;">${i + 1}</td>
                    <td style="padding-left:12px;font-size:14px;color:#374151;">${step}</td>
                  </tr></table>
                </td>
              </tr>`,
                )
                .join("")}
            </table>

            <p style="margin:0 0 16px;">
              If you have any questions in the meantime, please contact our admissions office at
              <a href="mailto:admissions@kibali.ac.ke" style="color:#f59e0b;text-decoration:none;font-weight:600;">admissions@kibali.ac.ke</a>
              or call <strong>+254 712 345 678</strong>.
            </p>
            <p style="margin:0;">Warm regards,<br/><strong>Kibali Academy Admissions Team</strong></p>
          </td>
        </tr>
        <!-- Footer -->
        <tr>
          <td style="background:#f8fafc;padding:20px 32px;border-top:1px solid #e2e8f0;">
            <p style="margin:0;font-size:11px;color:#94a3b8;text-align:center;">
              © ${new Date().getFullYear()} Kibali Academy · Lang'ata Road, Karen South, Nairobi<br/>
              This message was sent because an application was submitted for ${studentName}.
            </p>
          </td>
        </tr>
      </table>
    </td></tr>
  </table>
</body>
</html>`;
}

function buildAdminAlertEmail({
  studentName,
  parentName,
  ref,
  applyingForGrade,
  parentEmail,
  parentPhone,
}: {
  studentName: string;
  parentName: string;
  ref: string;
  applyingForGrade: string;
  parentEmail: string;
  parentPhone: string;
}): string {
  const siteUrl =
    process.env.NEXT_PUBLIC_SITE_URL ?? "https://portal.kibali.ac.ke";
  return `<!DOCTYPE html>
<html lang="en">
<head><meta charset="UTF-8"/></head>
<body style="margin:0;padding:0;background:#f1f5f9;font-family:'Segoe UI',Tahoma,sans-serif;">
  <table width="100%" cellpadding="0" cellspacing="0" border="0" style="background:#f1f5f9;padding:40px 16px;">
    <tr><td align="center">
      <table width="600" cellpadding="0" cellspacing="0" border="0" style="max-width:600px;width:100%;background:#ffffff;border-radius:16px;overflow:hidden;box-shadow:0 4px 24px rgba(0,0,0,0.08);">
        <tr><td style="background:#0c1f3f;padding:28px 32px;">
          <p style="margin:0;font-size:10px;font-weight:800;letter-spacing:0.14em;text-transform:uppercase;color:rgba(255,255,255,0.55);">Kibali Academy · Admin Alert</p>
          <p style="margin:6px 0 0;font-size:20px;font-weight:800;color:#ffffff;">New Admission Application</p>
        </td></tr>
        <tr><td style="height:4px;background:#f59e0b;"></td></tr>
        <tr>
          <td style="padding:32px;">
            <table width="100%" cellpadding="0" cellspacing="0" border="0" style="border:1px solid #e2e8f0;border-radius:10px;overflow:hidden;">
              ${[
                ["Reference", ref],
                ["Student", studentName],
                ["Applying For", applyingForGrade],
                ["Parent/Guardian", parentName],
                ["Email", parentEmail],
                ["Phone", parentPhone],
              ]
                .map(
                  ([label, value], i) => `
              <tr style="background:${i % 2 === 0 ? "#ffffff" : "#f8fafc"};">
                <td style="padding:12px 16px;font-size:12px;font-weight:700;text-transform:uppercase;letter-spacing:0.08em;color:#64748b;width:35%;">${label}</td>
                <td style="padding:12px 16px;font-size:14px;color:#1a202c;font-weight:500;">${value}</td>
              </tr>`,
                )
                .join("")}
            </table>

            <table width="100%" cellpadding="0" cellspacing="0" border="0" style="margin-top:24px;">
              <tr>
                <td align="center">
                  <a href="${siteUrl}/admin/applications" style="display:inline-block;background:#f59e0b;color:#0c1f3f;text-decoration:none;font-weight:800;font-size:13px;padding:14px 32px;border-radius:50px;letter-spacing:0.05em;">
                    Review Application →
                  </a>
                </td>
              </tr>
            </table>
          </td>
        </tr>
      </table>
    </td></tr>
  </table>
</body>
</html>`;
}
